#!/bin/bash
# =========================================================
#  CAÑAS - Deploy a PythonAnywhere (100% gratis, sin tarjeta)
# =========================================================
# PASOS MANUALES (no necesitas instalar nada)
#
echo "╔════════════════════════════════════════════════════════╗"
echo "║  🏋️  CAÑAS - Deploy a PythonAnywhere 🏋️             ║"
echo "║  100% gratis - Sin tarjeta de crédito                ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 1: Regístrate en PythonAnywhere"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Ve a https://www.pythonanywhere.com"
echo "2. Haz clic en 'Create a Beginner Account' (gratis)"
echo "3. Pon tu usuario, email y contraseña"
echo "   ⚠️  NO pide tarjeta de crédito"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 2: Sube el código"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Opción A (fácil): Desde el panel de PythonAnywhere:"
echo "  - Abre 'Files' → 'Upload a file'"
echo "  - Sube los archivos uno a uno (o usa git)"
echo ""
echo "Opción B (mejor): Usa Git desde la consola Bash:"
echo "   Desde la consola Bash de PythonAnywhere:"
echo "   git clone https://github.com/TU-USUARIO/canas.git"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 3: Crea un virtualenv e instala dependencias"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "En la consola Bash de PythonAnywhere:"
echo ""
echo "  cd canas"
echo "  python3 -m venv venv"
echo "  source venv/bin/activate"
echo "  pip install -r requirements.txt"
echo "  pip install aiosqlite  # SQLite para desarrollo"
echo "  python -m app.seed_exercises"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 4: Crea el archivo Web App"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Desde el panel: Web → Add a new web app"
echo "  - 'Manual configuration'"
echo "  - Python 3.12"
echo ""
echo "Luego, en la sección 'Code':"
echo "  - Source code: /home/TU_USUARIO/canas"
echo "  - Working directory: /home/TU_USUARIO/canas"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 5: Configura el archivo WSGI"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "En 'Code' → 'WSGI configuration file':"
echo "  Pega el contenido de pythonanywhere_wsgi.py"
echo "  (está en el repo como wsgi.py)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 6: Configura las variables de entorno"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "En la sección 'Environment variables':"
echo "  SECRET_KEY = (genera una: openssl rand -hex 32)"
echo "  DEBUG = false"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 7: Recarga y disfruta"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Haz clic en 'Reload TU_USUARIO.pythonanywhere.com'"
echo "y listo: https://TU_USUARIO.pythonanywhere.com"
echo ""
echo "📱 Funciona en PC y móvil desde el navegador"
echo ""
